# Generated by Django 4.2 on 2024-02-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vendedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('identidad', models.CharField(max_length=100, null=True, verbose_name='Descripcion')),
                ('telefono', models.CharField(max_length=12, null=True, verbose_name='Telefono')),
                ('correo', models.EmailField(max_length=254, null=True)),
                ('direccion', models.CharField(max_length=500, null=True)),
                ('fecha_ingreso', models.DateField(null=True)),
                ('estado', models.CharField(default='Activo', max_length=50, null=True)),
                ('doc_profesional', models.CharField(max_length=50, null=True, verbose_name='Colegiacion')),
                ('t_empleado', models.CharField(choices=[('0', 'Doctor'), ('1', 'Psicologo'), ('2', 'Secretario'), ('4', 'Administrador'), ('5', 'Vendedor')], max_length=200, null=True, verbose_name='Tipo de Empleado')),
            ],
        ),
    ]
