# Generated by Django 4.2 on 2024-02-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detalle_inv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventprod_id', models.IntegerField()),
                ('ordenes_id', models.IntegerField()),
            ],
            options={
                'db_table': 'facturacion_inventprod_orden_asociada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='facturas_formated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_factura', models.DateField()),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre paciente')),
                ('identidad', models.CharField(max_length=100, verbose_name='Identidad')),
                ('telefono', models.CharField(max_length=8, verbose_name='Numero de telefono')),
                ('direccion', models.CharField(max_length=500, verbose_name='Direccion del paciente')),
                ('vendedor', models.CharField(max_length=100, null=True, verbose_name='Vendedor')),
                ('factura', models.CharField(max_length=100, verbose_name='Numero de factura')),
                ('sub_total', models.CharField(max_length=100, verbose_name='SubTotal')),
                ('total_factura', models.FloatField()),
                ('descuento', models.FloatField()),
                ('impuesto', models.FloatField()),
                ('tipo_pago', models.CharField(max_length=100, null=True, verbose_name='Tipo de Pago')),
            ],
            options={
                'db_table': 'FACTURAS_FORMATED',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='adelantos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_adelanto', models.CharField(choices=[('0', 'Parcial'), ('1', 'Completo')], max_length=50, verbose_name='Tipo de Adelanto')),
                ('cantidad', models.FloatField()),
                ('tipo_solicitante', models.CharField(choices=[('0', 'Colaborador'), ('1', 'Empresa')], max_length=100, verbose_name='Tipo de Solicitante')),
                ('solicitante', models.CharField(max_length=500, verbose_name='Solicitante')),
                ('fecha_solicitud', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='detalleFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_factura', models.CharField(max_length=20, verbose_name='Fecha')),
                ('factura', models.CharField(max_length=100, verbose_name='Numero de factura')),
                ('cod_ord', models.CharField(max_length=100, verbose_name='Codigo de Orden')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Orden')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('cantidad', models.IntegerField()),
                ('sub_total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='encabezadoFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_factura', models.CharField(max_length=20, verbose_name='Fecha')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre paciente')),
                ('identidad', models.CharField(max_length=100, verbose_name='Identidad')),
                ('telefono', models.CharField(max_length=8, verbose_name='Numero de telefono')),
                ('direccion', models.CharField(max_length=500, verbose_name='Direccion del paciente')),
                ('vendedor', models.CharField(max_length=100, null=True, verbose_name='Vendedor')),
                ('factura', models.CharField(max_length=100, verbose_name='Numero de factura')),
                ('sub_total', models.CharField(max_length=100, verbose_name='SubTotal')),
                ('total_factura', models.FloatField()),
                ('descuento', models.FloatField()),
                ('impuesto', models.FloatField()),
                ('tipo_pago', models.CharField(max_length=100, null=True, verbose_name='Tipo de Pago')),
            ],
        ),
        migrations.CreateModel(
            name='examen_psi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=500, verbose_name='Ingrese la pregunta')),
                ('tipo_pregunta', models.CharField(choices=[('0', 'ITEMS DELIRIUM'), ('1', 'Ítems a evaluar Demencia'), ('2', 'Ítems para evaluar trastornos amnésicos y trastornos cognitivos'), ('3', 'Ítems para evaluar trastornos mentales debido a enfermedades medicas no clasificadas'), ('4', 'Ítems para evaluar esquizofrenia y otros trastornos psicóticos'), ('5', 'Ítems para evaluar trastornos del estado de animo'), ('6', 'Ítems para evaluar trastornos disociativos'), ('7', 'Ítems para evaluar trastornos del sueño de origen diferente al respiratorio'), ('8', 'Ítems para evaluar trastornos del control de impulsos'), ('9', 'Ítems para evaluar trastornos de la personalidad'), ('10', ' Ítems para evaluar trastorno del desarrollo intelectual'), ('11', 'Ítems para evaluar trastornos por déficit de atención'), ('12', 'Ítems para evaluar comportamiento perturbador')], max_length=10, verbose_name='Tipo de pregunta')),
                ('medicion_si', models.FloatField(verbose_name='Puntaje')),
                ('medicion_no', models.FloatField(verbose_name='Puntaje')),
            ],
        ),
        migrations.CreateModel(
            name='exaOpciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(max_length=100, verbose_name='opciones')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripcion opciones')),
            ],
        ),
        migrations.CreateModel(
            name='facturaFiscal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=100, verbose_name='Numero de Factura')),
            ],
        ),
        migrations.CreateModel(
            name='ordenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_ord', models.CharField(max_length=100, verbose_name='Codigo de Orden')),
                ('nombre_orden', models.CharField(max_length=100, verbose_name='Nombre de la Orden')),
                ('descripcion_orden', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('precio_orden', models.FloatField(verbose_name='Precio')),
                ('impuesto_orden', models.IntegerField(verbose_name='ISV')),
                ('encargado_orden', models.CharField(choices=[('0', 'Medico'), ('1', 'Psicologo'), ('2', 'Admin')], max_length=100, null=True, verbose_name='Encargado')),
                ('formulario', models.CharField(choices=[('0', 'Evaluacion Medica'), ('1', 'Evaluacion Psicologica'), ('3', 'Evaluacion Completa')], max_length=50, null=True, verbose_name='Formuarlio a Usar')),
            ],
        ),
        migrations.CreateModel(
            name='ordenes_emitidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_ord', models.CharField(max_length=100, verbose_name='Codigo de Orden')),
                ('nombre_orden', models.CharField(max_length=100, verbose_name='Nombre de la Orden')),
                ('encargado_orden', models.CharField(choices=[('0', 'Medico'), ('1', 'Psicologo'), ('2', 'Admin')], max_length=100, null=True, verbose_name='Encargado')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado orden')),
                ('fecha_emision', models.DateField(null=True)),
                ('fecha_cierre', models.DateTimeField(null=True)),
                ('paciente', models.CharField(max_length=100, null=True, verbose_name='Encargado')),
                ('formulario', models.CharField(choices=[('0', 'Evaluacion Medica'), ('1', 'Evaluacion Psicologica'), ('3', 'Evaluacion Completa')], max_length=50, null=True, verbose_name='Formuarlio a Usar')),
                ('dir_pac', models.CharField(max_length=500, null=True, verbose_name='Direccion')),
                ('identif_pac', models.CharField(max_length=500, null=True, verbose_name='Identificacion')),
                ('resultado', models.CharField(max_length=100, null=True, verbose_name='Resultado')),
            ],
        ),
        migrations.CreateModel(
            name='plant_variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_examen', models.CharField(max_length=100, verbose_name='Codigo del Examen')),
                ('nombre_examen', models.CharField(max_length=100, verbose_name='Nombre del Examen')),
                ('descripcion_examen', models.CharField(max_length=100, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='proveedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True, verbose_name='Proveedor')),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
    ]
