# Generated by Django 4.2 on 2024-02-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='cierre_diario_tot_mp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_factura', models.DateField()),
                ('tipo_pago', models.CharField(max_length=150, verbose_name='Productos')),
                ('total_ventas', models.FloatField()),
                ('cantidad_fact', models.IntegerField()),
            ],
            options={
                'db_table': 'rep_metodo_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='cierre_diario_tot_prod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_factura', models.DateField()),
                ('nombre', models.CharField(max_length=150, verbose_name='Productos')),
                ('total_facturado', models.FloatField()),
                ('total_ordenes', models.IntegerField()),
            ],
            options={
                'db_table': 'reporte_productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='cierre_diario_tot_vent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_factura', models.DateField()),
                ('total_ventas', models.FloatField()),
            ],
            options={
                'db_table': 'rep_total_ventas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='cierre_diario_vend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_factura', models.DateField()),
                ('vendedor', models.CharField(max_length=100, null=True, verbose_name='Vendedor')),
                ('monto_venta', models.FloatField()),
                ('total_facturas', models.PositiveIntegerField()),
                ('monto_adelanto', models.FloatField()),
                ('adelantos', models.PositiveIntegerField()),
                ('total_pago', models.FloatField()),
            ],
            options={
                'db_table': 'cierre_diario_vend',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='rep_arqueo_caja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField()),
                ('billete', models.CharField(max_length=5, verbose_name='Billete')),
                ('cantidad', models.IntegerField()),
                ('monto_total', models.IntegerField()),
            ],
            options={
                'db_table': 'resumen_arqueo_caja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='REPORTE_FACT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_factura', models.DateField()),
                ('nombre', models.CharField(max_length=100)),
                ('factura', models.CharField(max_length=100)),
                ('sub_total', models.FloatField(max_length=100)),
                ('descuento', models.FloatField(max_length=100)),
                ('impuesto', models.FloatField(max_length=100)),
                ('total_factura', models.FloatField(max_length=100)),
                ('vendedor', models.CharField(max_length=250)),
                ('identidad', models.CharField(max_length=100)),
                ('tipo_pago', models.IntegerField()),
            ],
            options={
                'db_table': 'reporte_fact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='REPORTE_PROD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_factura', models.DateField()),
                ('nombre', models.CharField(max_length=200)),
                ('total_facturado', models.FloatField()),
                ('total_ordenes', models.IntegerField()),
            ],
            options={
                'db_table': 'reporte_productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='REPORTE_VENTAS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_factura', models.DateField()),
                ('vendedor', models.CharField(max_length=100)),
                ('monto_venta', models.FloatField(max_length=100)),
                ('conteo', models.IntegerField()),
            ],
            options={
                'db_table': 'reporte_ventas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='arqueo_caja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(null=True)),
                ('billete', models.CharField(choices=[('1', 1), ('2', 2), ('5', 5), ('10', 10), ('20', 20), ('50', 50), ('100', 100), ('200', 200), ('500', 500)], max_length=3, null=True)),
                ('cantidad', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='info_facturas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_lim_em', models.CharField(max_length=10, null=True, verbose_name='DD-MM-YYYY')),
                ('numeracion', models.CharField(max_length=100, null=True, verbose_name='Numeracion Inicial Factura')),
                ('rango_inicial', models.IntegerField(verbose_name='Rango Inicial Autorizado')),
                ('rango_final', models.IntegerField(verbose_name='Rango Final Autorizado')),
                ('fac_actual', models.IntegerField(verbose_name='Siguiente Factura')),
                ('isv', models.IntegerField(null=True, verbose_name='Impuesto a cobrar')),
                ('sucursal', models.CharField(max_length=500, null=True, verbose_name='Sucursal')),
                ('cai', models.CharField(max_length=500, null=True, verbose_name='numero cai')),
            ],
        ),
        migrations.CreateModel(
            name='inventProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100, verbose_name='Producto')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion Producto')),
                ('cantidad_inv', models.PositiveIntegerField(verbose_name='Cantidad en Inventario')),
                ('precio', models.FloatField(verbose_name='Lps')),
                ('orden_asociada', models.ManyToManyField(to='ordenes.ordenes')),
            ],
        ),
    ]
