# Generated by Django 4.2 on 2024-03-07 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_inova', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario_log',
            options={},
        ),
    ]
