# Generated by Django 4.2 on 2024-03-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_inova', '0002_alter_usuario_log_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario_log',
            options={'managed': False},
        ),
    ]
