# Generated by Django 4.2 on 2024-02-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sucursales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sucursal', models.CharField(max_length=100, verbose_name='Sucursal')),
                ('direccion', models.CharField(max_length=500, null=True, verbose_name='Direccion')),
                ('rtn', models.CharField(max_length=100, null=True, verbose_name='RTN')),
                ('telefono', models.CharField(max_length=100, null=True, verbose_name='Telefono')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
