# Generated by Django 4.2 on 2024-02-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre paciente')),
                ('identidad', models.CharField(max_length=100, unique=True, verbose_name='Identidad')),
                ('telefono', models.CharField(max_length=8, verbose_name='Numero de telefono')),
                ('direccion', models.CharField(max_length=500, verbose_name='Direccion del paciente')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto')),
                ('huella', models.ImageField(blank=True, null=True, upload_to='', verbose_name='huella')),
                ('firma', models.ImageField(blank=True, null=True, upload_to='', verbose_name='firma')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pacOpciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(max_length=100, verbose_name='opciones')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripcion opciones')),
            ],
        ),
    ]
