# Generated by Django 4.2 on 2024-03-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
