# Generated by Django 4.2 on 2024-03-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_pacientes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
